# -*- coding: utf-8 -*-
"""erp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-nGvygsoXRevKgSOIlXcfr_o2QJTuwN
"""

import streamlit as st

# Configuración inicial
st.set_page_config(page_title="ERP Básico", layout="wide")

# Barra lateral para la navegación
st.sidebar.title("Módulos del ERP")
module = st.sidebar.radio("Selecciona un módulo:", ["Gestión de Inventarios", "Gestión de Nómina", "Reportes de Ventas"])

# Funciones de cada módulo
def gestion_inventarios():
    st.header("Gestión de Inventarios")
    st.write("Aquí puedes administrar los productos del inventario.")
    # Ejemplo: Mostrar una tabla básica
    productos = {"Producto": ["Laptop", "Teclado", "Mouse"],
                 "Cantidad": [10, 50, 100],
                 "Precio Unitario": [1000, 20, 10]}
    st.table(productos)

def gestion_nomina():
    st.header("Gestión de Nómina")
    st.write("Aquí puedes administrar los salarios de los empleados.")
    # Ejemplo: Captura de datos
    empleados = st.text_area("Ingresa la lista de empleados (nombre, salario):")
    if empleados:
        st.write("Datos capturados:")
        st.write(empleados)

def reportes_ventas():
    st.header("Reportes de Ventas")
    st.write("Aquí puedes visualizar los reportes de ventas.")
    # Ejemplo: Gráfico de ventas
    ventas = {"Mes": ["Enero", "Febrero", "Marzo"], "Ventas ($)": [5000, 7000, 8000]}
    st.bar_chart(data=ventas, x="Mes", y="Ventas ($)")

# Navegar entre los módulos
if module == "Gestión de Inventarios":
    gestion_inventarios()
elif module == "Gestión de Nómina":
    gestion_nomina()
elif module == "Reportes de Ventas":
    reportes_ventas()